# Generated by Django 5.1.15 on 2026-09-25 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday')),
                ('start_time', models.TimeField(help_text='Start time in teacher local clock, e.g. 09:00:00')),
                ('end_time', models.TimeField(help_text='End time in teacher local clock, e.g. 17:00:00')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Teacher Availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, help_text='e.g. Certified TEFL Tutor · 5+ Yrs Experience', max_length=255)),
                ('accent', models.CharField(choices=[('ZA', 'South African'), ('UK', 'British'), ('US', 'American'), ('OTHER', 'International')], db_index=True, default='ZA', max_length=10)),
                ('intro_video_url', models.URLField(blank=True, help_text='Cloudflare Stream HLS or preview MP4 URL')),
                ('intro_video_thumbnail', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('price_per_25min_usd', models.DecimalField(decimal_places=2, default=9.0, max_digits=6)),
                ('specialties', models.JSONField(default=list, help_text="List of tags: ['FreeTalk', 'Business English', 'Daily News', 'TOEIC']")),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
