# Generated by Django 5.1.15 on 2026-09-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='eskom_area_id',
            field=models.CharField(blank=True, default='jhb-block-3', max_length=64),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='has_inverter_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='sla_strikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
