# Generated by Django 5.1.15 on 2026-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacherprofile_eskom_area_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Teacher avatar image stored on Cloudflare R2', null=True, upload_to='teachers/avatars/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='intro_audio_file',
            field=models.FileField(blank=True, help_text='15s accent audio audition sample stored on R2', null=True, upload_to='teachers/audio/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='intro_audio_url',
            field=models.URLField(blank=True, help_text='Cloudflare R2 public audio URL'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tefl_certificate_file',
            field=models.FileField(blank=True, help_text='Private TEFL certificate stored securely on R2', null=True, upload_to='private/vetting/certificates/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tefl_certificate_url',
            field=models.URLField(blank=True, help_text='Direct or fallback certificate URL'),
        ),
    ]
