# Generated by Django 5.1.15 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('teachers', '0004_teacherprofile_avatar_image_and_more')]
    operations = [
        migrations.AlterField(
            model_name='teacherprofile', name='eskom_area_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='teacherprofile', name='has_lte_failover',
            field=models.BooleanField(default=False),
        ),
    ]
