# Generated by Django 5.1.15 on 2026-10-03 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_cancel_reason_booking_cancelled_at_and_more'),
        ('teachers', '0005_power_backup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStrike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('no_show', 'Missed a lesson'), ('late_cancel', 'Cancelled less than 24h before the lesson'), ('serial_cancel', 'Repeated early cancellations'), ('memo_sla', 'Memo not submitted within 24h')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_strikes', to='bookings.booking')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strikes', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking', 'kind'), name='uniq_strike_kind_per_booking')],
            },
        ),
    ]
