# Generated by Django 5.2.17 on 2026-10-05 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_teacherasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, help_text='Markdown shown to the tutor.')),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('is_required', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='teachers.trainingmodule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='teachers.teacherprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'module'), name='uniq_training_progress')],
            },
        ),
    ]
