# Generated by Django 5.2.17 on 2026-10-05 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_t6_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speed_test_download_mbps', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('speed_test_upload_mbps', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('speed_test_at', models.DateTimeField(blank=True, null=True)),
                ('power_backup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declaration_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='teachers.teacherprofile')),
            ],
        ),
    ]
