# Generated by Django 5.1.15 on 2026-09-25 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(help_text='Grammar corrections, speaking feedback, overall commentary')),
                ('vocabulary_words', models.JSONField(default=list, help_text="List of words: [{'word': 'resilience', 'definition': '...'}]")),
                ('pronunciation_notes', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='pending_payment', max_length=30)),
                ('start_time_utc', models.DateTimeField(db_index=True)),
                ('end_time_utc', models.DateTimeField()),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=64)),
                ('zoom_join_url', models.URLField(blank=True, max_length=512)),
                ('zoom_start_url', models.URLField(blank=True, max_length=1024)),
                ('zoom_password', models.CharField(blank=True, max_length=32)),
                ('teacher_gcal_event_id', models.CharField(blank=True, max_length=255)),
                ('student_rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 star rating', null=True)),
                ('student_review', models.TextField(blank=True, help_text='Written review visible to admin and teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='materials.material')),
            ],
            options={
                'ordering': ['-start_time_utc'],
            },
        ),
    ]
