# Generated by Django 5.1.15 on 2026-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('interrupted_power', 'Interrupted (Power Outage)')], db_index=True, default='pending_payment', max_length=30),
        ),
    ]
