# Generated by Django 5.1.15 on 2026-09-30 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_email', models.EmailField(max_length=254)),
                ('join_time_utc', models.DateTimeField()),
                ('leave_time_utc', models.DateTimeField(blank=True, null=True)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_audits', to='bookings.booking')),
            ],
            options={
                'ordering': ['-join_time_utc'],
            },
        ),
    ]
