# Generated by Django 5.1.15 on 2026-09-30 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_attendanceaudit'),
        ('materials', '0001_initial'),
        ('teachers', '0003_teacherprofile_eskom_area_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_teacher_active_timeslot',
        ),
        migrations.AddField(
            model_name='booking',
            name='escrow_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='memo_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_10m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor_late_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('interrupted_power', 'Interrupted (Power Outage)'), ('student_no_show', 'Student No Show'), ('teacher_no_show', 'Teacher No Show'), ('completed_pending_memo', 'Completed (Pending Memo)'), ('completed_memo_forfeited', 'Completed (Memo Forfeited)')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'in_progress', 'completed', 'completed_pending_memo', 'completed_memo_forfeited'])), fields=('teacher', 'start_time_utc'), name='unique_teacher_active_timeslot'),
        ),
    ]
