# Generated by Django 5.1.15 on 2026-09-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_unique_teacher_active_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceaudit',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='zoom_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='attendanceaudit',
            name='join_time_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
