# Generated by Django 5.1.15 on 2026-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmemo',
            name='grammar_notes',
            field=models.TextField(blank=True, help_text='Grammar points to remember (shown to the student next to the vocabulary)'),
        ),
    ]
