# Generated by Django 5.1.15 on 2026-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_lessonmemo_grammar_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_review_tags',
            field=models.JSONField(blank=True, default=list, help_text='Rubric tags the student picked (services.reviews.REVIEW_TAGS)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student_review',
            field=models.TextField(blank=True, help_text='PRIVATE written review: staff only. Never shown to the tutor or other students.'),
        ),
    ]
