# Generated by Django 5.1.15 on 2026-10-03 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_attendance_identity_and_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_start_time_utc',
            field=models.DateTimeField(blank=True, help_text='Where the lesson started out, before its first reschedule', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('interrupted_power', 'Interrupted (Power Outage)'), ('student_no_show', 'Student No Show'), ('teacher_no_show', 'Teacher No Show'), ('completed_pending_memo', 'Completed (Pending Memo)'), ('completed_memo_forfeited', 'Completed (Memo Forfeited)'), ('cancelled_by_student', 'Cancelled by Student (refunded)'), ('student_late_cancelled', 'Cancelled by Student (late, fee kept)'), ('cancelled_by_teacher', 'Cancelled by Tutor (refunded)')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.CreateModel(
            name='BookingReschedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_start_time_utc', models.DateTimeField()),
                ('new_start_time_utc', models.DateTimeField()),
                ('actor', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
