# Generated by Django 5.1.15 on 2026-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_slot_lock_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceaudit',
            name='identity',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='zoom_session_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddConstraint(
            model_name='attendanceaudit',
            constraint=models.UniqueConstraint(condition=models.Q(('zoom_session_id', ''), _negated=True), fields=('booking', 'zoom_session_id'), name='uniq_attendance_session_per_booking'),
        ),
    ]
