# Generated by Django 5.1.15 on 2026-10-02 21:19

from django.db import migrations, models


def classify_existing_attendance(apps, schema_editor):
    AttendanceAudit = apps.get_model('bookings', 'AttendanceAudit')
    for row in AttendanceAudit.objects.select_related('booking__teacher__user', 'booking__student').iterator():
        email = (row.participant_email or '').strip().lower()
        teacher_email = (row.booking.teacher.user.email or '').strip().lower()
        student_email = (row.booking.student.email or '').strip().lower()
        classification = 'teacher' if email and email == teacher_email else ('student' if email and email == student_email else 'unknown')
        payload = row.raw_payload if isinstance(row.raw_payload, dict) else {}
        AttendanceAudit.objects.filter(pk=row.pk).update(
            classification=classification,
            participant_id=str(payload.get('id') or '')[:128],
            registrant_id=str(payload.get('registrant_id') or '')[:128],
            host_id=str(payload.get('host_id') or '')[:128],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_attendance_identity_and_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceaudit',
            name='classification',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='host_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='participant_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='registrant_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.RunPython(classify_existing_attendance, migrations.RunPython.noop),
    ]
