# Generated by Django 5.2.17 on 2026-10-05 07:36

import apps.common.clock
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0013_booking_cancel_reason_booking_cancelled_at_and_more'),
        ('users', '0005_grace_failure_runbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_by_kind', models.JSONField(blank=True, default=dict)),
                ('in_app_by_kind', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Ids only, never free text (plan §3.2).')),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('in_app', models.BooleanField(default=True, help_text='Shown in the in-app list (False = e-mail-only row).')),
                ('created_at', models.DateTimeField(default=apps.common.clock.now, editable=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending (claimed; the lease is NOTIFICATION_LEASE_SECONDS)'), ('sent', 'Sent'), ('retryable', 'Retryable'), ('failed', 'Failed (needs a person)'), ('skipped', 'Skipped (no e-mail for this kind / preference)'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=12)),
                ('email_attempts', models.PositiveSmallIntegerField(default=0)),
                ('email_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('email_first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('email_next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('rendered_subject', models.CharField(blank=True, max_length=255)),
                ('rendered_html', models.TextField(blank=True)),
                ('rendered_text', models.TextField(blank=True)),
                ('email_last_error', models.CharField(blank=True, help_text='Short code only, never a provider body.', max_length=64)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notif_user_read_created'), models.Index(fields=['email_state', 'email_next_attempt_at'], name='notif_email_due')],
            },
        ),
    ]
