# Generated by Django 5.1.15 on 2026-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True once the user proved control of `email` (verification or password-reset link).'),
        ),
    ]
