# Generated by Django 5.1 on 2026-10-03

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_student_profiles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    StudentProfile = apps.get_model('users', 'StudentProfile')
    StudentProfile.objects.bulk_create(
        [StudentProfile(user_id=user_id) for user_id in User.objects.filter(role='student').values_list('id', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('target_level', models.CharField(blank=True, max_length=64)),
                ('learning_goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('delivery_state', models.CharField(choices=[('pending', 'Pending'), ('retryable', 'Retryable'), ('sent', 'Sent')], db_index=True, default='pending', max_length=20)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('last_delivery_error', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.RunPython(create_student_profiles, migrations.RunPython.noop),
    ]
