# Generated by Django 5.2.17 on 2026-10-03 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_supportinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportinquiry',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('payment_failure', 'Payment failure')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='related_booking_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='related_transaction_ref',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='supportinquiry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
