# Generated by Django 5.2.17 on 2026-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_supportinquiry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_blocked_reason',
            field=models.CharField(blank=True, help_text='Non-empty = the student cannot book (e.g. a lesson was delivered but its payment failed). Staff clear it.', max_length=255),
        ),
    ]
