/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/attendance/live/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_admin_attendance_live_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disputes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_admin_disputes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disputes/{id}/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_admin_disputes_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/finance/ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_admin_finance_ledger_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/payouts/batch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_admin_payouts_batch_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/payouts/execute-batch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_admin_payouts_execute_batch_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teachers/{id}/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_admin_teachers_verify_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/teachers/pending-vetting/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_admin_teachers_pending_vetting_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/telemetry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_admin_telemetry_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Blacklists the supplied refresh token so it can no longer mint access tokens.
         *
         *     Deliberately not gated on a live access token: the refresh token is itself the proof of ownership, and an
         *     expired access token must not leave a 14-day refresh token impossible to revoke.
         */
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_auth_me_retrieve"];
        put: operations["v1_auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/password-change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Always answers 202 with the same body, whether or not the address belongs to an account (no enumeration).
         *     The e-mail is sent by a Celery task after commit, so response time does not reveal it either.
         */
        post: operations["v1_auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description (Re)send the verification e-mail for the signed-in user's current address. */
        post: operations["v1_auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_verify_email_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My lessons (students: lessons I booked; tutors: my roster) */
        get: operations["v1_bookings_list"];
        put?: never;
        post: operations["v1_bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The student or the tutor cancels a lesson. Refunds, bonus credit and strikes follow the D-6 policy (see
         *     docs/CANCELLATION_AND_REFUNDS.md). A student cancelling inside the free window must send acknowledge_forfeit=true.
         */
        post: operations["v1_bookings_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/cancel-preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What would happen if I cancelled now? Read-only: shown before the student/tutor confirms. */
        get: operations["v1_bookings_cancel_preview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/memo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The lesson's own tutor submits (or later corrects) the post-lesson memo. Everything below succeeds or fails together:
         *     the validated memo, the booking's move to COMPLETED, and the student's flashcards.
         */
        post: operations["v1_bookings_memo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/report-outage/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The lesson's tutor (or staff) reports an Eskom load-shedding / grid outage around the lesson (D-6):
         *     1. Marks the booking INTERRUPTED_POWER.
         *     2. Queues a full gateway refund for the student (they may convert it to wallet credit). The tutor is not paid and gets no strike.
         *     A student cannot file this report (it would refund them while the tutor goes unpaid): a student problem goes through a dispute.
         *     A lesson the tutor taught for the minimum lesson time is a delivered lesson, not an outage.
         */
        post: operations["v1_bookings_report_outage_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/reschedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The student moves a paid, still-future lesson to another open slot of the same tutor (once, more than 2 hours before it
         *     starts). The booking keeps its id, payment and escrow. Tutors who cannot teach a lesson cancel it instead.
         */
        post: operations["v1_bookings_reschedule_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @deprecated
         * @description Old URL (POST /bookings/<id>/review/), kept for existing clients; identical behaviour.
         */
        post: operations["v1_bookings_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_bookings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/reserve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Validates a slot, takes the 10-minute Redis hold and creates the PENDING_PAYMENT booking in one step.
         *     The returned `booking_id` is what checkout pays for. Retrying the same request returns the existing live hold.
         */
        post: operations["v1_bookings_reserve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/slots/{teacher_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns concrete 25-minute slots for a given teacher projected into the requested timezone. */
        get: operations["v1_bookings_slots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/r2/presigned-url/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/integrations/storage/presigned-url/
         *     POST /api/v1/integrations/r2/presigned-url/
         *     Generates presigned upload or download URLs for Cloudflare R2 object storage with zero egress fees.
         *     Direct-to-storage client upload architecture eliminates backend Gunicorn/Celery worker blocking.
         *     Enforces strict role-based access control (RBAC), Tier 1 vs Tier 2 separation, and path traversal protection.
         */
        post: operations["v1_integrations_r2_presigned_url_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/storage/presigned-url/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/v1/integrations/storage/presigned-url/
         *     POST /api/v1/integrations/r2/presigned-url/
         *     Generates presigned upload or download URLs for Cloudflare R2 object storage with zero egress fees.
         *     Direct-to-storage client upload architecture eliminates backend Gunicorn/Celery worker blocking.
         *     Enforces strict role-based access control (RBAC), Tier 1 vs Tier 2 separation, and path traversal protection.
         */
        post: operations["v1_integrations_storage_presigned_url_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_materials_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_materials_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/checkout/init/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Initializes checkout for PayFast (ZAR) or PayPal (USD). Persists an INITIALIZED transaction holding the
         *     server-computed expected amount; webhooks are verified against it, never against client/gateway-supplied totals.
         */
        post: operations["v1_payments_checkout_init_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/credits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_payments_credits_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refunds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_refunds_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/refunds/{refund_id}/convert-to-wallet/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Turn a still-pending gateway refund into 30-day wallet credit (instead of waiting for the card/PayPal refund). */
        post: operations["v1_refunds_convert_to_wallet_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/bookings/{id}/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description A student rates a lesson that took place: 1-5 stars, optional rubric tags and private notes. One review per lesson;
         *     the written text is private to staff. Canonical URL: POST /student/bookings/<id>/review/.
         */
        post: operations["v1_student_bookings_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/flashcards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_student_flashcards_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/flashcards/{id}/mastery/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_student_flashcards_mastery_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_student_lessons_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/student/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_student_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_student_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/teacher/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_teacher_students_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teacher/students/{student_id}/dossier/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["v1_teacher_students_dossier_partial_update"];
        trace?: never;
    };
    "/api/v1/teachers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_teachers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_teachers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/availability/manage/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_teachers_availability_manage_list"];
        put?: never;
        post: operations["v1_teachers_availability_manage_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `ZA` - South African
         *     * `UK` - British
         *     * `US` - American
         *     * `OTHER` - International
         * @enum {string}
         */
        AccentEnum: "ZA" | "UK" | "US" | "OTHER";
        BookingCreate: {
            /** Format: uuid */
            readonly id: string;
            /** Format: date-time */
            start_time_utc: string;
            readonly status: components["schemas"]["BookingStatusEnum"];
        };
        BookingCreateRequest: {
            /** Format: uuid */
            teacher_id: string;
            /** Format: uuid */
            material_id?: string | null;
            /** Format: date-time */
            start_time_utc: string;
        };
        BookingDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly booking_reference: string;
            readonly teacher: components["schemas"]["TeacherList"];
            readonly student: components["schemas"]["BookingStudent"];
            /** Format: uuid */
            readonly material: string | null;
            readonly material_slug: string | null;
            readonly material_title: string | null;
            /** @default pending_payment */
            readonly status: components["schemas"]["BookingStatusEnum"];
            /** Format: date-time */
            readonly start_time_utc: string;
            /** Format: date-time */
            readonly end_time_utc: string;
            readonly local_date: string;
            readonly local_start_time: string;
            readonly local_end_time: string;
            readonly viewer_timezone: string;
            /** Format: double */
            readonly price_usd: number;
            /** Format: double */
            readonly price_zar: number;
            readonly lock_expires_at: string | null;
            readonly zoom_url: string;
            readonly zoom_join_url: string;
            readonly zoom_start_url: string;
            readonly zoom_meeting_id: string;
            readonly zoom_password: string;
            /** @description 1 to 5 star rating */
            readonly student_rating: number | null;
            /** @description PRIVATE written review: staff only. Never shown to the tutor or other students. */
            readonly student_review: string;
            readonly memo: components["schemas"]["LessonMemo"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly cancelled_at: string | null;
            readonly reschedule_count: number;
            /**
             * Format: date-time
             * @description Where the lesson started out, before its first reschedule
             */
            readonly original_start_time_utc: string | null;
        };
        /**
         * @description * `pending_payment` - Pending Payment
         *     * `confirmed` - Confirmed
         *     * `in_progress` - In Progress
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         *     * `disputed` - Disputed
         *     * `interrupted_power` - Interrupted (Power Outage)
         *     * `student_no_show` - Student No Show
         *     * `teacher_no_show` - Teacher No Show
         *     * `completed_pending_memo` - Completed (Pending Memo)
         *     * `completed_memo_forfeited` - Completed (Memo Forfeited)
         *     * `cancelled_by_student` - Cancelled by Student (refunded)
         *     * `student_late_cancelled` - Cancelled by Student (late, fee kept)
         *     * `cancelled_by_teacher` - Cancelled by Tutor (refunded)
         * @enum {string}
         */
        BookingStatusEnum: "pending_payment" | "confirmed" | "in_progress" | "completed" | "cancelled" | "disputed" | "interrupted_power" | "student_no_show" | "teacher_no_show" | "completed_pending_memo" | "completed_memo_forfeited" | "cancelled_by_student" | "student_late_cancelled" | "cancelled_by_teacher";
        /** @description Minimal student view embedded in a booking. Contact details are only for the student themselves/staff. */
        BookingStudent: {
            /** Format: uuid */
            id: string;
            readonly full_name: string;
            first_name: string;
            timezone: string;
            country: string;
        };
        CancelPreview: {
            can_cancel: boolean;
            outcome: string;
            message: string;
            seconds_until_start: number;
            refund_amount: string | null;
            refund_currency: string | null;
            bonus_credits: number;
            strike: boolean;
            /** Format: date-time */
            free_cancel_until?: string;
        };
        CancelRequestRequest: {
            /** @default  */
            reason: string;
            /** @default false */
            acknowledge_forfeit: boolean;
        };
        CancelResult: {
            outcome: string;
            status: string;
            message: string;
        };
        /**
         * @description * `daily_news` - Daily News & Discussion
         *     * `freetalk` - FreeTalk Conversation Prompts
         *     * `business` - Business English & Professional
         *     * `test_prep` - Job Interview & Test Prep
         * @enum {string}
         */
        CategoryEnum: "daily_news" | "freetalk" | "business" | "test_prep";
        /**
         * @description * `A1` - Beginner A1
         *     * `A2` - Elementary A2
         *     * `B1` - Intermediate B1
         *     * `B2` - Upper-Intermediate B2
         *     * `C1` - Advanced C1
         *     * `C2` - Proficient C2
         * @enum {string}
         */
        CefrLevelEnum: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
        CreditBundleRow: {
            pack_name: string;
            remaining: number;
            total: number;
            /** Format: date-time */
            purchased_at: string;
            /** Format: date-time */
            expires_at: string | null;
        };
        CreditLedgerEntry: {
            id: string;
            description: string;
            credits_delta: number;
            /** Format: date */
            date: string;
            type: components["schemas"]["TypeEnum"];
        };
        CustomTokenObtainPairRequest: {
            username: string;
            password: string;
        };
        Detail: {
            detail: string;
        };
        EmailVerifyConfirmRequest: {
            token: string;
        };
        ErrorCode: {
            error: string;
            code: string;
        };
        LessonMemo: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly booking: string;
            /** Format: uuid */
            readonly teacher: string;
            /** Format: uuid */
            readonly student: string;
            /** @description Grammar corrections, speaking feedback, overall commentary */
            feedback_text: string;
            /** @description List of words: [{'word': 'resilience', 'definition': '...'}] */
            vocabulary_words?: unknown;
            pronunciation_notes?: string;
            /** @description Grammar points to remember (shown to the student next to the vocabulary) */
            grammar_notes?: string;
            homework?: string;
            /** Format: date-time */
            readonly submitted_at: string;
        };
        /**
         * @description What a tutor may submit after a lesson. Unknown keys (e.g. the UI's `booking_id`, `next_steps`) are ignored.
         *     (DRF's CharField already rejects NUL characters - PostgreSQL cannot store them; the vocabulary items are checked by hand.)
         */
        LessonMemoInputRequest: {
            feedback_text: string;
            vocabulary_words?: unknown[];
            /** @default  */
            pronunciation_notes: string;
            /** @default  */
            grammar_notes: string;
            /** @default  */
            homework: string;
        };
        LogoutRequestRequest: {
            refresh: string;
        };
        MaterialDetail: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            slug: string;
            category: components["schemas"]["CategoryEnum"];
            readonly category_display: string;
            cefr_level: components["schemas"]["CefrLevelEnum"];
            readonly cefr_display: string;
            description?: string;
            readonly pdf_file_url: string;
            readonly audio_snippet_url: string;
            /** @description Structured HTML content: article text, vocab definitions, discussion questions */
            content_html?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        MaterialList: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            slug: string;
            category: components["schemas"]["CategoryEnum"];
            readonly category_display: string;
            cefr_level: components["schemas"]["CefrLevelEnum"];
            readonly cefr_display: string;
            description?: string;
            readonly pdf_file_url: string;
            readonly audio_snippet_url: string;
        };
        PaginatedBookingDetailList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BookingDetail"][];
        };
        PaginatedMaterialListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MaterialList"][];
        };
        PaginatedRefundList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Refund"][];
        };
        PaginatedTeacherAvailabilityList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TeacherAvailability"][];
        };
        PaginatedTeacherListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TeacherList"][];
        };
        PasswordChangeRequest: {
            new_password: string;
            new_password_confirm: string;
            old_password: string;
        };
        PasswordResetConfirmRequest: {
            new_password: string;
            new_password_confirm: string;
            uid: string;
            token: string;
        };
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        PatchedUserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @description ISO 3166-1 alpha-2 code (e.g. ZA, JP, KR, DE) */
            country?: string;
            /** @description IANA Timezone, e.g. Asia/Tokyo */
            timezone?: string;
            phone_number?: string;
        };
        Refund: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly booking_id: string;
            /** Format: decimal */
            readonly amount: string;
            readonly currency: string;
            readonly reason: components["schemas"]["RefundReasonEnum"];
            readonly status: components["schemas"]["RefundStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly processed_at: string | null;
        };
        /**
         * @description * `student_cancel` - Student cancelled in time
         *     * `teacher_cancel` - Tutor cancelled
         *     * `teacher_no_show` - Tutor did not attend
         *     * `outage` - Power outage interrupted the lesson
         *     * `dispute` - Dispute decided for the student
         * @enum {string}
         */
        RefundReasonEnum: "student_cancel" | "teacher_cancel" | "teacher_no_show" | "outage" | "dispute";
        /**
         * @description * `pending_gateway` - Waiting for the gateway
         *     * `processed` - Paid to the original payment method
         *     * `converted` - Converted to wallet credit
         *     * `failed` - Gateway refused (needs a human)
         * @enum {string}
         */
        RefundStatusEnum: "pending_gateway" | "processed" | "converted" | "failed";
        Register: {
            /** Format: uuid */
            readonly id: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            /** @default student */
            role: components["schemas"]["RegisterRoleEnum"];
            /** @description ISO 3166-1 alpha-2 code (e.g. ZA, JP, KR, DE) */
            country?: string;
            /** @description IANA Timezone, e.g. Asia/Tokyo */
            timezone?: string;
        };
        RegisterRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
            first_name?: string;
            last_name?: string;
            /** @default student */
            role: components["schemas"]["RegisterRoleEnum"];
            /** @description ISO 3166-1 alpha-2 code (e.g. ZA, JP, KR, DE) */
            country?: string;
            /** @description IANA Timezone, e.g. Asia/Tokyo */
            timezone?: string;
        };
        /**
         * @description * `student` - student
         *     * `teacher` - teacher
         * @enum {string}
         */
        RegisterRoleEnum: "student" | "teacher";
        RescheduleRequestRequest: {
            /** Format: date-time */
            start_time_utc: string;
        };
        Reservation: {
            /** Format: uuid */
            booking_id: string;
            status: string;
            /** Format: uuid */
            teacher_id: string;
            /** Format: date-time */
            start_time_utc: string;
            /** Format: date-time */
            end_time_utc: string;
            lock_ttl_seconds: number;
            /** Format: date-time */
            lock_expires_at: string;
            message: string;
        };
        ReserveRequestRequest: {
            /** Format: uuid */
            teacher_id: string;
            /** Format: date-time */
            start_time_utc: string;
        };
        /** @description A student's review. `review` is the legacy name of `private_notes` (older clients). */
        ReviewInputRequest: {
            rating: number;
            tags?: components["schemas"]["TagsEnum"][];
            /** @default  */
            private_notes: string;
            /** @default  */
            review: string;
        };
        ReviewResult: {
            success: boolean;
            status: string;
            message: string;
        };
        /**
         * @description * `Patience & Empathy` - Patience & Empathy
         *     * `Clear Pronunciation` - Clear Pronunciation
         *     * `Great Corrections` - Great Corrections
         *     * `Conversational Flow` - Conversational Flow
         *     * `Encouraging Atmosphere` - Encouraging Atmosphere
         *     * `Deep Topic Expertise` - Deep Topic Expertise
         *     * `Ideal Pacing` - Ideal Pacing
         *     * `Helpful Examples` - Helpful Examples
         * @enum {string}
         */
        TagsEnum: "Patience & Empathy" | "Clear Pronunciation" | "Great Corrections" | "Conversational Flow" | "Encouraging Atmosphere" | "Deep Topic Expertise" | "Ideal Pacing" | "Helpful Examples";
        TeacherAvailability: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Format: int64
             * @description 0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday
             */
            day_of_week: number;
            /**
             * Format: time
             * @description Start time in teacher local clock, e.g. 09:00:00
             */
            start_time: string;
            /**
             * Format: time
             * @description End time in teacher local clock, e.g. 17:00:00
             */
            end_time: string;
            is_active?: boolean;
        };
        TeacherAvailabilityRequest: {
            /**
             * Format: int64
             * @description 0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday
             */
            day_of_week: number;
            /**
             * Format: time
             * @description Start time in teacher local clock, e.g. 09:00:00
             */
            start_time: string;
            /**
             * Format: time
             * @description End time in teacher local clock, e.g. 17:00:00
             */
            end_time: string;
            is_active?: boolean;
        };
        TeacherDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user_id: string;
            readonly full_name: string;
            readonly first_name: string;
            readonly last_name: string;
            /** @description e.g. Certified TEFL Tutor · 5+ Yrs Experience */
            headline?: string;
            accent?: components["schemas"]["AccentEnum"];
            intro_video_thumbnail?: string;
            readonly avatar_url: string;
            readonly intro_audio_url: string;
            /** Format: decimal */
            rating_avg?: string;
            /** Format: int64 */
            rating_count?: number;
            /** Format: decimal */
            price_per_25min_usd?: string;
            /** @description List of tags: ['FreeTalk', 'Business English', 'Daily News', 'TOEIC'] */
            specialties?: unknown;
            readonly country: string;
            is_verified?: boolean;
            bio?: string;
            /** @description Cloudflare Stream HLS or preview MP4 URL */
            intro_video_url?: string;
            readonly timezone: string;
            readonly availabilities: components["schemas"]["TeacherAvailability"][];
        };
        TeacherList: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user_id: string;
            readonly full_name: string;
            readonly first_name: string;
            readonly last_name: string;
            /** @description e.g. Certified TEFL Tutor · 5+ Yrs Experience */
            headline?: string;
            accent?: components["schemas"]["AccentEnum"];
            intro_video_thumbnail?: string;
            readonly avatar_url: string;
            readonly intro_audio_url: string;
            /** Format: decimal */
            rating_avg?: string;
            /** Format: int64 */
            rating_count?: number;
            /** Format: decimal */
            price_per_25min_usd?: string;
            /** @description List of tags: ['FreeTalk', 'Business English', 'Daily News', 'TOEIC'] */
            specialties?: unknown;
            readonly country: string;
            is_verified?: boolean;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        /**
         * @description * `purchase` - purchase
         *     * `redemption` - redemption
         *     * `refund` - refund
         *     * `bonus` - bonus
         * @enum {string}
         */
        TypeEnum: "purchase" | "redemption" | "refund" | "bonus";
        User: {
            /** Format: uuid */
            readonly id: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            /** @description True once the user proved control of `email` (verification or password-reset link). */
            readonly email_verified: boolean;
            first_name?: string;
            last_name?: string;
            readonly role: components["schemas"]["UserRoleEnum"];
            /** @description ISO 3166-1 alpha-2 code (e.g. ZA, JP, KR, DE) */
            country?: string;
            /** @description IANA Timezone, e.g. Asia/Tokyo */
            timezone?: string;
            phone_number?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** @description Remaining lesson credits (students only; otherwise null). */
            readonly credits: number | null;
            /** @description Tutor profile photo URL (tutors only; otherwise empty). */
            readonly avatar_url: string;
            /** @description Vetting status (tutors only; otherwise null). */
            readonly is_verified: boolean | null;
        };
        UserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @description ISO 3166-1 alpha-2 code (e.g. ZA, JP, KR, DE) */
            country?: string;
            /** @description IANA Timezone, e.g. Asia/Tokyo */
            timezone?: string;
            phone_number?: string;
        };
        /**
         * @description * `student` - Student
         *     * `teacher` - Teacher
         *     * `admin` - Administrator
         * @enum {string}
         */
        UserRoleEnum: "student" | "teacher" | "admin";
        Wallet: {
            total_credits: number;
            ledger: components["schemas"]["CreditLedgerEntry"][];
            bundles: components["schemas"]["CreditBundleRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_admin_attendance_live_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_disputes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_disputes_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_finance_ledger_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_payouts_batch_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_payouts_execute_batch_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_teachers_verify_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_teachers_pending_vetting_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_telemetry_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequestRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    v1_auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    v1_auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    v1_auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["CustomTokenObtainPairRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    v1_auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    v1_auth_verify_email_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailVerifyConfirmRequest"];
                "multipart/form-data": components["schemas"]["EmailVerifyConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    v1_bookings_list: {
        parameters: {
            query?: {
                /** @description Lessons starting on/after this UTC date (YYYY-MM-DD) or ISO date-time. */
                from?: string;
                /** @description Default: soonest first for when=upcoming, newest first otherwise. */
                ordering?: "-start_time_utc" | "start_time_utc";
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description 1-100 (default 20). */
                page_size?: number;
                /** @description One or more booking statuses, comma-separated or repeated. */
                status?: string;
                /** @description Lessons starting on/before this UTC date (whole day) or ISO date-time. */
                to?: string;
                /** @description upcoming = not yet ended, excluding cancelled and lapsed unpaid holds; past = already ended. */
                when?: "past" | "upcoming";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBookingDetailList"];
                };
            };
        };
    };
    v1_bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BookingCreateRequest"];
                "multipart/form-data": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingCreate"];
                };
            };
        };
    };
    v1_bookings_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CancelRequestRequest"];
                "multipart/form-data": components["schemas"]["CancelRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorCode"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorCode"];
                };
            };
        };
    };
    v1_bookings_cancel_preview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelPreview"];
                };
            };
        };
    };
    v1_bookings_memo_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonMemoInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonMemoInputRequest"];
                "multipart/form-data": components["schemas"]["LessonMemoInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonMemo"];
                };
            };
        };
    };
    v1_bookings_report_outage_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_bookings_reschedule_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RescheduleRequestRequest"];
                "multipart/form-data": components["schemas"]["RescheduleRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorCode"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorCode"];
                };
            };
        };
    };
    v1_bookings_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReviewInputRequest"];
                "multipart/form-data": components["schemas"]["ReviewInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResult"];
                };
            };
        };
    };
    v1_bookings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
        };
    };
    v1_bookings_reserve_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReserveRequestRequest"];
                "multipart/form-data": components["schemas"]["ReserveRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    v1_bookings_slots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_integrations_r2_presigned_url_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_integrations_storage_presigned_url_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_materials_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMaterialListList"];
                };
            };
        };
    };
    v1_materials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetail"];
                };
            };
        };
    };
    v1_payments_checkout_init_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_payments_credits_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
        };
    };
    v1_refunds_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRefundList"];
                };
            };
        };
    };
    v1_refunds_convert_to_wallet_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                refund_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    v1_student_bookings_review_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReviewInputRequest"];
                "multipart/form-data": components["schemas"]["ReviewInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResult"];
                };
            };
        };
    };
    v1_student_flashcards_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_student_flashcards_mastery_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_student_lessons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_student_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_student_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_teacher_students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_teacher_students_dossier_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_teachers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeacherListList"];
                };
            };
        };
    };
    v1_teachers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherDetail"];
                };
            };
        };
    };
    v1_teachers_availability_manage_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTeacherAvailabilityList"];
                };
            };
        };
    };
    v1_teachers_availability_manage_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherAvailabilityRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TeacherAvailabilityRequest"];
                "multipart/form-data": components["schemas"]["TeacherAvailabilityRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherAvailability"];
                };
            };
        };
    };
}
