# Generated by Django 5.1.15 on 2026-09-30 17:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFlashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(db_index=True, max_length=128)),
                ('phonetic', models.CharField(blank=True, max_length=128)),
                ('part_of_speech', models.CharField(blank=True, max_length=64)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('lesson_source', models.CharField(blank=True, help_text='e.g. High-Stakes Contract Negotiations (Sharon M.)', max_length=255)),
                ('mastery', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], db_index=True, default='new', max_length=20)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('next_review_due', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_due', 'created_at'],
            },
        ),
    ]
