# Generated by Django 5.1.15 on 2026-09-25 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('daily_news', 'Daily News & Discussion'), ('freetalk', 'FreeTalk Conversation Prompts'), ('business', 'Business English & Professional'), ('test_prep', 'Job Interview & Test Prep')], db_index=True, max_length=32)),
                ('cefr_level', models.CharField(choices=[('A1', 'Beginner A1'), ('A2', 'Elementary A2'), ('B1', 'Intermediate B1'), ('B2', 'Upper-Intermediate B2'), ('C1', 'Advanced C1'), ('C2', 'Proficient C2')], db_index=True, max_length=4)),
                ('description', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True, help_text='Structured HTML content: article text, vocab definitions, discussion questions')),
                ('pdf_file_url', models.URLField(blank=True, help_text='Cloudflare R2 link for student/teacher worksheet download')),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cefr_level', 'title'],
            },
        ),
    ]
