# Generated by Django 5.1.15 on 2026-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='audio_snippet_file',
            field=models.FileField(blank=True, help_text='Listening comprehension audio file stored on R2', null=True, upload_to='materials/audio/'),
        ),
        migrations.AddField(
            model_name='material',
            name='audio_snippet_url',
            field=models.URLField(blank=True, help_text='Direct Cloudflare R2 audio stream link'),
        ),
        migrations.AddField(
            model_name='material',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Direct upload worksheet PDF to Cloudflare R2 ($0 egress)', null=True, upload_to='materials/pdfs/'),
        ),
    ]
