# Generated by Django 5.2.17 on 2026-10-06 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutbatch',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutbatch',
            name='exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_batches_exported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payoutbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('exported', 'Exported'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PayoutBatchLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_zar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('exported', 'Exported'), ('paid', 'Paid'), ('returned', 'Returned by the bank'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('skip_reason', models.CharField(blank=True, max_length=64)),
                ('account_fingerprint', models.CharField(blank=True, max_length=64)),
                ('account_last_four', models.CharField(blank=True, max_length=4)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='admin_api.payoutbatch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_lines', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('returned', 'Returned')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='admin_api.payoutbatchline')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutExportAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_count', models.PositiveIntegerField()),
                ('content_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_audits', to='admin_api.payoutbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payoutbatchline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('teacher',), name='payout_one_open_line_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatchline',
            constraint=models.UniqueConstraint(fields=('batch', 'teacher'), name='payout_one_line_per_teacher_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='payoutbatchline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_zar__gte', 0)), name='payout_line_amount_not_negative'),
        ),
    ]
