# Generated by Django 5.1.15 on 2026-10-03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('bookings', '0012_attendanceaudit_classification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='EskomAreaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(max_length=128, unique=True)),
                ('area_name', models.CharField(max_length=255)),
                ('stage', models.PositiveSmallIntegerField()),
                ('outages', models.JSONField(default=list)),
                ('provider_status', models.CharField(choices=[('ok', 'OK'), ('stale', 'Stale'), ('quota', 'Quota exhausted'), ('error', 'Provider error')], default='ok', max_length=16)),
                ('provider_retrieved_at', models.DateTimeField()),
                ('fresh_until', models.DateTimeField()),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EskomNotificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('retryable', 'Retryable')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.eskomareastatus')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eskom_notifications', to='bookings.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

