# Generated by Django 5.1.15 on 2026-09-30 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTutorDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private_pedagogical_notes', models.TextField(blank=True, help_text='Confidential notes on student progress, learning style, and focus areas')),
                ('common_grammar_mistakes', models.JSONField(default=list, help_text="List of recurring grammar slips: ['articles', 'conditionals']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_dossiers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_dossiers', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'student'), name='unique_teacher_student_dossier')],
            },
        ),
    ]
