# Generated by Django 5.1.15 on 2026-09-25 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_name', models.CharField(default='5-Lesson Pack', max_length=64)),
                ('total_credits', models.PositiveIntegerField(default=5)),
                ('remaining_credits', models.PositiveIntegerField(default=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('payfast', 'PayFast (ZAR)'), ('paypal', 'PayPal (USD/EUR/JPY)')], max_length=20)),
                ('gateway_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='initialized', max_length=20)),
                ('raw_webhook_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
