# Generated by Django 5.1.15 on 2026-09-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='escrow_cleared',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
