# Generated by Django 5.1.15 on 2026-10-01 18:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
        ('bookings', '0006_attendanceaudit_raw_payload_and_more'),
        ('payments', '0003_paymenttransaction_escrow_cleared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_batch_id', models.UUIDField(db_index=True, help_text='Groups balancing debits and credits of a single transaction')),
                ('account', models.CharField(choices=[('1010_asset_gateway_payfast', '1010 - Asset: Gateway Cash (PayFast ZAR)'), ('1020_asset_gateway_paypal', '1020 - Asset: Gateway Cash (PayPal USD)'), ('1030_asset_operating_bank', '1030 - Asset: Operating Bank Cash (ZAR)'), ('2010_liability_student_escrow', '2010 - Liability: Student Escrow Deposits'), ('2020_liability_tutor_payable', '2020 - Liability: Tutor Payables'), ('2030_liability_quarantine_deposit', '2030 - Liability: Quarantined Late Deposits'), ('4010_revenue_platform_commission', '4010 - Revenue: Platform Take Rate (20%)'), ('5010_expense_dispute_settlement', '5010 - Expense: Platform Dispute Settlements'), ('5020_expense_student_compensation', '5020 - Expense: Student Goodwill / Compensation'), ('5030_expense_gateway_fees', '5030 - Expense: Payment Gateway Processing Fees')], db_index=True, max_length=64)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit (DR)'), ('credit', 'Credit (CR)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fx_rate_to_zar', models.DecimalField(decimal_places=4, default=Decimal('18.7500'), max_digits=10)),
                ('amount_zar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('event_type', models.CharField(choices=[('payment_captured', 'Payment Captured'), ('escrow_cleared', 'Escrow Cleared (Dual-Verified)'), ('payout_executed', 'Tutor EFT Payout Executed'), ('refund_issued', 'Refund Issued'), ('dispute_resolved', 'Dispute Resolved'), ('compensation_awarded', 'Apology / Goodwill Compensation'), ('outage_refund', 'Eskom Outage Force Majeure Refund'), ('late_payment_quarantine', 'DEF-501 Late Payment Quarantine')], db_index=True, max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='bookings.booking')),
                ('dispute_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='admin_api.disputecase')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.paymenttransaction')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='admin_api.payoutbatch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['journal_batch_id'], name='payments_le_journal_1e4871_idx'), models.Index(fields=['account', 'created_at'], name='payments_le_account_cef3e5_idx'), models.Index(fields=['event_type', 'created_at'], name='payments_le_event_t_e5663a_idx')],
            },
        ),
    ]
