# Generated by Django 5.1.15 on 2026-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_ledgerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('1010_asset_gateway_payfast', '1010 - Asset: Gateway Cash (PayFast ZAR)'), ('1020_asset_gateway_paypal', '1020 - Asset: Gateway Cash (PayPal USD)'), ('1030_asset_operating_bank', '1030 - Asset: Operating Bank Cash (ZAR)'), ('2010_liability_student_escrow', '2010 - Liability: Student Escrow Deposits'), ('2020_liability_tutor_payable', '2020 - Liability: Tutor Payables'), ('2030_liability_quarantine_deposit', '2030 - Liability: Quarantined Late Deposits'), ('2040_liability_student_wallet', '2040 - Liability: Student Wallet Credits'), ('4010_revenue_platform_commission', '4010 - Revenue: Platform Take Rate (20%)'), ('5010_expense_dispute_settlement', '5010 - Expense: Platform Dispute Settlements'), ('5020_expense_student_compensation', '5020 - Expense: Student Goodwill / Compensation'), ('5030_expense_gateway_fees', '5030 - Expense: Payment Gateway Processing Fees')], db_index=True, max_length=64),
        ),
    ]
