# Generated by Django 5.1.15 on 2026-10-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_ledgerentry_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
