# Generated by Django 5.1.15 on 2026-10-02 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_attendanceaudit_raw_payload_and_more'),
        ('payments', '0006_paymenttransaction_merchant_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('payment_captured', 'Payment Captured'), ('escrow_cleared', 'Escrow Cleared (Dual-Verified)'), ('payout_executed', 'Tutor EFT Payout Executed'), ('refund_issued', 'Refund Issued'), ('dispute_resolved', 'Dispute Resolved'), ('compensation_awarded', 'Apology / Goodwill Compensation'), ('outage_refund', 'Eskom Outage Force Majeure Refund'), ('late_payment_quarantine', 'DEF-501 Late Payment Quarantine'), ('unallocated_payment', 'Unallocated / Duplicate Payment Held for Refund')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('unallocated', 'Unallocated (refund pending)')], db_index=True, default='initialized', max_length=20),
        ),
        migrations.CreateModel(
            name='GatewayAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('payfast', 'PayFast (ZAR)'), ('paypal', 'PayPal (USD/EUR/JPY)')], max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('reason', models.CharField(db_index=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_anomalies', to='bookings.booking')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
