# Generated by Django 5.1.15 on 2026-10-02 20:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


CATALOG = (
    ('bundle_1', 'Single Lesson', 1, '8.00', '150.00', '7.50', '1200.00'),
    ('bundle_5', 'Starter Pack', 5, '38.00', '700.00', '35.50', '5700.00'),
    ('bundle_10', 'Fluency Builder', 10, '72.00', '1300.00', '67.00', '10800.00'),
    ('bundle_20', 'Mastery Intensive', 20, '136.00', '2400.00', '127.00', '20400.00'),
)


def seed_and_backfill(apps, schema_editor):
    CreditPack = apps.get_model('payments', 'CreditPack')
    CreditBundle = apps.get_model('payments', 'CreditBundle')
    CreditWalletEntry = apps.get_model('payments', 'CreditWalletEntry')
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    BookingFunding = apps.get_model('payments', 'BookingFunding')

    packs = {}
    for order, (code, name, credits, usd, zar, eur, jpy) in enumerate(CATALOG):
        packs[credits], _ = CreditPack.objects.update_or_create(
            code=code,
            defaults={
                'name': name, 'credits': credits, 'price_usd': Decimal(usd),
                'price_zar': Decimal(zar), 'price_eur': Decimal(eur),
                'price_jpy': Decimal(jpy), 'display_order': order, 'is_active': True,
            },
        )

    currency_rates = {
        'USD': Decimal('18.750000'),
        'ZAR': Decimal('1.000000'),
        'EUR': Decimal('20.000000'),
        'JPY': Decimal('0.125000'),
    }
    running_balances = {}
    for bundle in CreditBundle.objects.order_by('user_id', 'created_at', 'id'):
        total = max(bundle.total_credits, 1)
        unit = (bundle.amount_paid / Decimal(total)).quantize(Decimal('0.01'))
        rate = currency_rates.get(bundle.currency.upper(), Decimal('1.000000'))
        CreditBundle.objects.filter(pk=bundle.pk).update(
            unit_amount=unit, fx_rate_to_zar=rate, fx_source='legacy_catalog_backfill')
        balance = running_balances.get(bundle.user_id, 0) + bundle.remaining_credits
        running_balances[bundle.user_id] = balance
        CreditWalletEntry.objects.create(
            user_id=bundle.user_id, bundle_id=bundle.id, entry_type='opening',
            credit_delta=bundle.remaining_credits, balance_after=balance,
            amount=(unit * bundle.remaining_credits).quantize(Decimal('0.01')),
            currency=bundle.currency.upper(), fx_rate_to_zar=rate,
            fx_source='legacy_catalog_backfill',
            description=f'Opening balance: {bundle.pack_name}',
            idempotency_key=f'opening:{bundle.id}',
        )

    for tx in PaymentTransaction.objects.filter(status='success', booking_id__isnull=False).order_by('created_at'):
        if BookingFunding.objects.filter(booking_id=tx.booking_id).exists():
            continue
        currency = tx.currency.upper()
        BookingFunding.objects.create(
            booking_id=tx.booking_id, source_type='gateway', captured_amount=tx.amount,
            currency=currency, fx_rate_to_zar=currency_rates.get(currency, Decimal('1.000000')),
            fx_source='legacy_capture_backfill', payment_transaction_id=tx.id,
        )


def reverse_seed(apps, schema_editor):
    CreditPack = apps.get_model('payments', 'CreditPack')
    CreditPack.objects.filter(code__in=[row[0] for row in CATALOG]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_slot_lock_token'),
        ('payments', '0007_unallocated_payments_and_gateway_anomaly'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('credits', models.PositiveSmallIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_zar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_jpy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'credits'],
            },
        ),
        migrations.CreateModel(
            name='CreditWalletEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Pack purchase'), ('redemption', 'Lesson redemption'), ('refund', 'Operational refund'), ('bonus', 'Operational bonus')], db_index=True, max_length=20)),
                ('credit_delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fx_rate_to_zar', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('fx_source', models.CharField(default='legacy_opening', max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='fx_rate_to_zar',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='fx_source',
            field=models.CharField(default='legacy_opening', max_length=64),
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bookings.booking'),
        ),
        migrations.CreateModel(
            name='BookingFunding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('gateway', 'Gateway payment'), ('credit', 'Wallet credit')], max_length=20)),
                ('captured_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('fx_rate_to_zar', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fx_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funding', to='bookings.booking')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_funding', to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('fx_rate_to_zar', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fx_source', models.CharField(default='credit_catalog', max_length=64)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='initialized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='payments.creditpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='credit_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_bundle', to='payments.creditpurchase'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='credit_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.creditpurchase'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('credit_purchase__isnull', True)), models.Q(('booking__isnull', True), ('credit_purchase__isnull', False)), _connector='OR'), name='payment_transaction_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='creditwalletentry',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_wallet_entries', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='creditwalletentry',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to='payments.creditbundle'),
        ),
        migrations.AddField(
            model_name='creditwalletentry',
            name='credit_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_entries', to='payments.creditpurchase'),
        ),
        migrations.AddField(
            model_name='creditwalletentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_wallet_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingfunding',
            name='credit_wallet_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_funding', to='payments.creditwalletentry'),
        ),
        migrations.AddField(
            model_name='settlementanomaly',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_anomalies', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingfunding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_transaction__isnull', False), ('credit_wallet_entry__isnull', True)), models.Q(('payment_transaction__isnull', True), ('credit_wallet_entry__isnull', False)), _connector='OR'), name='booking_funding_exactly_one_source'),
        ),
        migrations.RunPython(seed_and_backfill, reverse_seed),
    ]
