# Generated by Django 5.1.15 on 2026-10-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_creditpack_creditwalletentry_settlementanomaly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('payment_captured', 'Payment Captured'), ('credit_redeemed', 'Credit Redeemed into Escrow'), ('escrow_cleared', 'Escrow Cleared (Dual-Verified)'), ('payout_executed', 'Tutor EFT Payout Executed'), ('refund_issued', 'Refund Issued'), ('dispute_resolved', 'Dispute Resolved'), ('compensation_awarded', 'Apology / Goodwill Compensation'), ('outage_refund', 'Eskom Outage Force Majeure Refund'), ('late_payment_quarantine', 'DEF-501 Late Payment Quarantine'), ('unallocated_payment', 'Unallocated / Duplicate Payment Held for Refund')], db_index=True, max_length=40),
        ),
    ]
