# Generated by Django 5.1.15 on 2026-10-02 20:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_capture_fx(apps, schema_editor):
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    BookingFunding = apps.get_model('payments', 'BookingFunding')
    CreditPurchase = apps.get_model('payments', 'CreditPurchase')
    for tx in PaymentTransaction.objects.all().iterator():
        rate = None
        source = ''
        if tx.booking_id:
            funding = BookingFunding.objects.filter(booking_id=tx.booking_id).first()
            if funding:
                rate, source = funding.fx_rate_to_zar, funding.fx_source
        elif tx.credit_purchase_id:
            purchase = CreditPurchase.objects.filter(pk=tx.credit_purchase_id).first()
            if purchase:
                rate, source = purchase.fx_rate_to_zar, purchase.fx_source
        if rate is None:
            currency = tx.currency.upper()
            if currency == 'ZAR':
                rate, source = Decimal('1.000000'), 'legacy_transaction_currency'
            elif currency == 'USD':
                rate, source = Decimal('18.750000'), 'legacy_configured_rate'
        if rate is not None:
            PaymentTransaction.objects.filter(pk=tx.pk).update(fx_rate_to_zar=rate, fx_source=source)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_slot_lock_token'),
        ('payments', '0009_alter_ledgerentry_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='fx_source',
            field=models.CharField(default='legacy_default', max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fx_rate_to_zar',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fx_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_fee_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='fx_rate_to_zar',
            field=models.DecimalField(decimal_places=6, default=Decimal('18.750000'), max_digits=12),
        ),
        migrations.RunPython(backfill_capture_fx, migrations.RunPython.noop),
        migrations.CreateModel(
            name='FulfillmentDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending dispatch'), ('queued', 'Queued'), ('running', 'Running'), ('retryable', 'Retryable failure'), ('succeeded', 'Succeeded'), ('failed', 'Terminal failure')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('zoom_completed', models.BooleanField(default=False)),
                ('calendar_completed', models.BooleanField(default=False)),
                ('email_completed', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_dispatch', to='bookings.booking')),
            ],
        ),
    ]
