# Generated by Django 5.1 on 2026-10-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0011_ledgerentry_database_immutability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPayoutAccount',
            fields=[
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='payout_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('encrypted_payload', models.TextField()),
                ('key_version', models.CharField(max_length=32)),
                ('account_last_four', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
