# Generated by Django 5.1.15 on 2026-10-03 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_cancel_reason_booking_cancelled_at_and_more'),
        ('payments', '0012_tutorpayoutaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbundle',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='expired_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='creditbundle',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchased pack'), ('refund', 'Refund converted to credit'), ('bonus', 'Goodwill / compensation bonus'), ('restitution', 'Restitution (failed booking)')], default='purchase', max_length=16),
        ),
        migrations.AlterField(
            model_name='creditwalletentry',
            name='entry_type',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Pack purchase'), ('redemption', 'Lesson redemption'), ('refund', 'Operational refund'), ('bonus', 'Operational bonus'), ('expiry', 'Credits expired')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('1010_asset_gateway_payfast', '1010 - Asset: Gateway Cash (PayFast ZAR)'), ('1020_asset_gateway_paypal', '1020 - Asset: Gateway Cash (PayPal USD)'), ('1030_asset_operating_bank', '1030 - Asset: Operating Bank Cash (ZAR)'), ('2010_liability_student_escrow', '2010 - Liability: Student Escrow Deposits'), ('2020_liability_tutor_payable', '2020 - Liability: Tutor Payables'), ('2030_liability_quarantine_deposit', '2030 - Liability: Quarantined Late Deposits'), ('2040_liability_student_wallet', '2040 - Liability: Student Wallet Credits'), ('2050_liability_refunds_payable', '2050 - Liability: Gateway Refunds Payable'), ('4010_revenue_platform_commission', '4010 - Revenue: Platform Take Rate (20%)'), ('4020_revenue_credit_breakage', '4020 - Revenue: Expired Credit Breakage'), ('5010_expense_dispute_settlement', '5010 - Expense: Platform Dispute Settlements'), ('5020_expense_student_compensation', '5020 - Expense: Student Goodwill / Compensation'), ('5030_expense_gateway_fees', '5030 - Expense: Payment Gateway Processing Fees')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('payment_captured', 'Payment Captured'), ('credit_redeemed', 'Credit Redeemed into Escrow'), ('escrow_cleared', 'Escrow Cleared (Dual-Verified)'), ('payout_executed', 'Tutor EFT Payout Executed'), ('refund_issued', 'Refund Issued'), ('dispute_resolved', 'Dispute Resolved'), ('compensation_awarded', 'Apology / Goodwill Compensation'), ('outage_refund', 'Eskom Outage Force Majeure Refund'), ('late_payment_quarantine', 'DEF-501 Late Payment Quarantine'), ('unallocated_payment', 'Unallocated / Duplicate Payment Held for Refund'), ('gateway_refund_paid', 'Gateway Refund Paid to Original Payment Method'), ('credit_expired', 'Wallet Credit Expired (breakage)')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(choices=[('student_cancel', 'Student cancelled in time'), ('teacher_cancel', 'Tutor cancelled'), ('teacher_no_show', 'Tutor did not attend'), ('outage', 'Power outage interrupted the lesson'), ('dispute', 'Dispute decided for the student')], max_length=20)),
                ('status', models.CharField(choices=[('pending_gateway', 'Waiting for the gateway'), ('processed', 'Paid to the original payment method'), ('converted', 'Converted to wallet credit'), ('failed', 'Gateway refused (needs a human)')], db_index=True, default='pending_gateway', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('failure_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='bookings.booking')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'reason'), name='uniq_refund_per_booking_reason')],
            },
        ),
    ]
