# Generated by Django 5.2.17 on 2026-10-03 13:05

from decimal import Decimal

from django.db import migrations, models


# PROVISIONAL launch prices (D-1: platform-set flat price per currency); change in the admin, never in code.
PROVISIONAL_PRICES = (('USD', '9.00'), ('EUR', '8.50'), ('ZAR', '162.00'), ('JPY', '1350.00'))


def seed_prices(apps, schema_editor):
    LessonPrice = apps.get_model('payments', 'LessonPrice')
    for currency, amount in PROVISIONAL_PRICES:
        LessonPrice.objects.get_or_create(currency=currency, defaults={'amount': Decimal(amount)})


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_backfill_credit_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPrice',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='lessonprice_amount_positive')],
            },
        ),
        migrations.RunPython(seed_prices, migrations.RunPython.noop),
    ]
