# Generated by Django 5.2.17 on 2026-10-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_ledgerentry_fx_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('rate_to_zar', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate_to_zar__gt', 0)), name='fxrate_rate_positive')],
            },
        ),
    ]
