# Generated by Django 5.2.17 on 2026-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_fxrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pending_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='bookingfunding',
            name='source_type',
            field=models.CharField(choices=[('gateway', 'Gateway payment'), ('gateway_pending', 'Gateway payment pending clearance'), ('credit', 'Wallet credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('pending_capture', 'Pending capture (not yet guaranteed)'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('unallocated', 'Unallocated (refund pending)')], db_index=True, default='initialized', max_length=20),
        ),
    ]
