# Generated by Django 5.2.17 on 2026-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_paymenttransaction_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfunding',
            name='source_type',
            field=models.CharField(choices=[('gateway', 'Gateway payment'), ('gateway_pending', 'Gateway payment pending clearance'), ('platform_absorbed', 'Payment failed; platform absorbs the tutor share'), ('credit', 'Wallet credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('1010_asset_gateway_payfast', '1010 - Asset: Gateway Cash (PayFast ZAR)'), ('1020_asset_gateway_paypal', '1020 - Asset: Gateway Cash (PayPal USD)'), ('1030_asset_operating_bank', '1030 - Asset: Operating Bank Cash (ZAR)'), ('2010_liability_student_escrow', '2010 - Liability: Student Escrow Deposits'), ('2020_liability_tutor_payable', '2020 - Liability: Tutor Payables'), ('2030_liability_quarantine_deposit', '2030 - Liability: Quarantined Late Deposits'), ('2040_liability_student_wallet', '2040 - Liability: Student Wallet Credits'), ('2050_liability_refunds_payable', '2050 - Liability: Gateway Refunds Payable'), ('4010_revenue_platform_commission', '4010 - Revenue: Platform Take Rate (20%)'), ('4020_revenue_credit_breakage', '4020 - Revenue: Expired Credit Breakage'), ('5010_expense_dispute_settlement', '5010 - Expense: Platform Dispute Settlements'), ('5020_expense_student_compensation', '5020 - Expense: Student Goodwill / Compensation'), ('5030_expense_gateway_fees', '5030 - Expense: Payment Gateway Processing Fees'), ('5040_expense_absorbed_payment_failure', '5040 - Expense: Platform-Absorbed Payment Failure (tutor paid, student never paid)')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('payment_captured', 'Payment Captured'), ('credit_redeemed', 'Credit Redeemed into Escrow'), ('escrow_cleared', 'Escrow Cleared (Dual-Verified)'), ('payout_executed', 'Tutor EFT Payout Executed'), ('refund_issued', 'Refund Issued'), ('dispute_resolved', 'Dispute Resolved'), ('compensation_awarded', 'Apology / Goodwill Compensation'), ('outage_refund', 'Eskom Outage Force Majeure Refund'), ('late_payment_quarantine', 'DEF-501 Late Payment Quarantine'), ('unallocated_payment', 'Unallocated / Duplicate Payment Held for Refund'), ('gateway_refund_paid', 'Gateway Refund Paid to Original Payment Method'), ('credit_expired', 'Wallet Credit Expired (breakage)'), ('payment_failure_absorbed', 'Tutor Paid by Platform After Pending Payment Failed')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('awaiting_clearance', 'Waiting for the payment to clear'), ('void', 'Not needed (the payment never cleared)'), ('pending_gateway', 'Waiting for the gateway'), ('processed', 'Paid to the original payment method'), ('converted', 'Converted to wallet credit'), ('failed', 'Gateway refused (needs a human)')], db_index=True, default='pending_gateway', max_length=20),
        ),
    ]
