# Task 10.7 slice R-B: refund claim/retry protocol columns, the SUBMITTED status and the append-only RefundAttempt table.
#
# Safe on Postgres: every new RefundRequest column is nullable or has a constant default (an instant metadata change on
# PG 11+, no table rewrite), the one index is on a small table and RefundAttempt is brand new. Fully reversible (all
# operations are schema-only; the status AlterField only changes Django-side choices). Rows that failed before this
# migration keep failure_kind '' and are treated as ambiguous by retry_failed (an admin must confirm).
# Generated by Django 5.2.17 on 2026-10-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_cancel_reason_booking_cancelled_at_and_more'),
        ('payments', '0019_grace_failure_runbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('send', 'Sent to the gateway'), ('poll', 'Polled the gateway'), ('admin_retry', 'Retried by an admin'), ('admin_mark_paid', 'Marked paid by an admin')], max_length=16)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('result_state', models.CharField(blank=True, max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['refund_id', 'seq'],
            },
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='claim_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='claimed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='failure_kind',
            field=models.CharField(blank=True, choices=[('rejected', 'The provider refused it'), ('already_refunded', 'The provider says the payment is already fully refunded'), ('guard', 'A safety check refused it before any call'), ('exhausted', 'Retries ran out'), ('replay_window', 'Too old to replay blind'), ('provider_failed', 'The provider failed it after accepting it')], max_length=24),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='first_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='gateway_request_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='last_http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='request_epoch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('awaiting_clearance', 'Waiting for the payment to clear'), ('void', 'Not needed (the payment never cleared)'), ('pending_gateway', 'Waiting for the gateway'), ('submitted', 'On its way'), ('processed', 'Paid to the original payment method'), ('converted', 'Converted to wallet credit'), ('failed', 'Gateway refused (needs a human)')], db_index=True, default='pending_gateway', max_length=20),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'next_attempt_at'], name='refund_status_next_idx'),
        ),
        migrations.AddField(
            model_name='refundattempt',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundattempt',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_log', to='payments.refundrequest'),
        ),
        migrations.AddConstraint(
            model_name='refundattempt',
            constraint=models.UniqueConstraint(fields=('refund', 'seq'), name='uniq_refund_attempt_seq'),
        ),
    ]
