# Task 10.7 QA M5: RefundAttempt.kind gains webhook / convert / guard / mark_failed. Choices only: no SQL is run (Django-side
# validation list), so it is safe on Postgres and trivially reversible.
# Generated by Django 5.2.17 on 2026-10-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_refund_claim_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundattempt',
            name='kind',
            field=models.CharField(choices=[('send', 'Sent to the gateway'), ('poll', 'Polled the gateway'), ('admin_retry', 'Retried by an admin'), ('admin_mark_paid', 'Marked paid by an admin'), ('webhook', 'Completed by a PayPal webhook'), ('convert', 'Converted to wallet credit'), ('guard', 'Stopped by a safety guard before sending'), ('mark_failed', 'Marked failed')], max_length=16),
        ),
    ]
