# Generated by Django 5.2.17 on 2026-10-04 12:01
# Slice F0: FulfillmentDispatch gains a compare-and-swap claim (claim_token, claimed_at), per-step states and the ABANDONED status.
# Additive and defaulted. The data step copies the legacy *_completed booleans into the new step states (True -> done); its
# reverse is a no-op because the booleans are left untouched and remain the legacy mirror.

from django.db import migrations, models


def backfill_step_states(apps, schema_editor):
    Dispatch = apps.get_model('payments', 'FulfillmentDispatch')
    for flag, state in (('zoom_completed', 'zoom_state'), ('calendar_completed', 'calendar_state'),
                        ('email_completed', 'email_state')):
        Dispatch.objects.filter(**{flag: True}).update(**{state: 'done'})


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_refund_attempt_more_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentdispatch',
            name='calendar_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped (nothing to do, e.g. no Google Calendar connected)'), ('failed', 'Failed (retried)')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='fulfillmentdispatch',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='fulfillmentdispatch',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmentdispatch',
            name='email_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped (nothing to do, e.g. no Google Calendar connected)'), ('failed', 'Failed (retried)')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='fulfillmentdispatch',
            name='zoom_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped (nothing to do, e.g. no Google Calendar connected)'), ('failed', 'Failed (retried)')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='fulfillmentdispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending dispatch'), ('queued', 'Queued'), ('running', 'Running'), ('retryable', 'Retryable failure'), ('succeeded', 'Succeeded'), ('failed', 'Terminal failure'), ('abandoned', 'Abandoned: booking no longer confirmed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_step_states, migrations.RunPython.noop),
    ]
