# Generated by Django 5.2.17 on 2026-10-06 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_payout_batches'),
        ('bookings', '0017_r1_retention_index'),
        ('payments', '0023_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='event_type',
            field=models.CharField(choices=[('payment_captured', 'Payment Captured'), ('credit_redeemed', 'Credit Redeemed into Escrow'), ('escrow_cleared', 'Escrow Cleared (Dual-Verified)'), ('payout_executed', 'Tutor EFT Payout Executed'), ('refund_issued', 'Refund Issued'), ('dispute_resolved', 'Dispute Resolved'), ('compensation_awarded', 'Apology / Goodwill Compensation'), ('outage_refund', 'Eskom Outage Force Majeure Refund'), ('late_payment_quarantine', 'DEF-501 Late Payment Quarantine'), ('unallocated_payment', 'Unallocated / Duplicate Payment Held for Refund'), ('gateway_refund_paid', 'Gateway Refund Paid to Original Payment Method'), ('credit_expired', 'Wallet Credit Expired (breakage)'), ('payment_failure_absorbed', 'Tutor Paid by Platform After Pending Payment Failed'), ('payout_returned', 'Tutor EFT Payout Returned by the Bank (reversal)')], db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_batch__isnull', False)), fields=('payout_batch', 'user', 'account', 'event_type'), name='ledger_one_payout_posting_per_tutor_batch'),
        ),
    ]
